/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "inverse-primary": "#79db8d",
        "surface-dim": "#dadad9",
        "on-surface-variant": "#3f493f",
        "surface-container-high": "#e8e8e7",
        "outline": "#6f7a6e",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#653e00",
        "on-primary-fixed": "#00210a",
        "tertiary-fixed": "#ffd9dd",
        "tertiary-container": "#b64c62",
        "secondary-fixed-dim": "#ffb95f",
        "inverse-on-surface": "#f1f1f0",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#400013",
        "on-tertiary": "#ffffff",
        "primary": "#00652c",
        "surface": "#f9f9f8",
        "on-secondary-fixed": "#2a1700",
        "secondary": "#855300",
        "secondary-fixed": "#ffddb8",
        "surface-tint": "#006d30",
        "on-primary-fixed-variant": "#005323",
        "primary-fixed-dim": "#79db8d",
        "on-primary": "#ffffff",
        "tertiary": "#97344a",
        "surface-variant": "#e2e2e2",
        "inverse-surface": "#2f3130",
        "secondary-container": "#fea619",
        "error": "#ba1a1a",
        "outline-variant": "#becabc",
        "background": "#f9f9f8",
        "on-secondary": "#ffffff",
        "on-primary-container": "#d3ffd5",
        "on-tertiary-fixed-variant": "#81233b",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "surface-container": "#eeeeed",
        "on-secondary-container": "#684000",
        "surface-bright": "#f9f9f8",
        "on-tertiary-container": "#fff1f1",
        "primary-fixed": "#95f8a7",
        "primary-container": "#15803d",
        "surface-container-low": "#f3f4f3",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb2bd"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"],
        "display": ["Outfit"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
